[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
